apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: ${{ values.name }}
  description: Postgres database (Database API, size ${{ values.size }}).
spec:
  type: database
  owner: group:${{ values.team }}
  dependsOn: [api:database-api]
