#!/usr/bin/env python3
"""Embed each platform/apis/<api>/compose.py into its composition.yaml, and
each definition.yaml into catalog/apis.yaml (Backstage API entities).

compose.py is the source of truth (it has unit tests); composition.yaml is
generated so function-python can run it. CI runs this with --check and fails
if the committed composition is stale.

Usage: scripts/gen-compositions.py [--check]
"""

import pathlib
import sys
import textwrap

ROOT = pathlib.Path(__file__).resolve().parent.parent
APIS = ROOT / "platform" / "apis"

# One entry per API: directory -> (composition name, XR kind).
COMPOSITIONS = {
    "database": ("database-cnpg", "Database"),
    "webservice": ("webservice-kubernetes", "WebService"),
}

TEMPLATE = """\
# GENERATED by scripts/gen-compositions.py from compose.py. Do not edit.
apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: {name}
spec:
  compositeTypeRef:
    apiVersion: platform.fernhill.io/v1alpha1
    kind: {kind}
  mode: Pipeline
  pipeline:
    - step: compose
      functionRef:
        name: function-python
      input:
        apiVersion: python.fn.crossplane.io/v1beta1
        kind: Script
        script: |
{script}"""


def render(api: str) -> str:
    name, kind = COMPOSITIONS[api]
    script = (APIS / api / "compose.py").read_text()
    return TEMPLATE.format(name=name, kind=kind, script=textwrap.indent(script, " " * 10))


# API entities for the portal (ADR-0011). Backstage can't resolve $text
# placeholders relative to file locations, so the XRD is embedded instead.
API_ENTITIES = {
    "database": ("database-api", "Database API", "A t-shirt-sized Postgres database.", "0006-database-api-and-python-compositions.md"),
    "webservice": ("webservice-api", "WebService API", "Run a long-running HTTP service on the paved road.", "0008-webservice-api.md"),
}

API_TEMPLATE = """\
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: {name}
  title: {title}
  description: {description}
  links:
    - url: https://github.com/NicPucacco/aidp/blob/main/docs/adr/{adr}
      title: Decision record
spec:
  type: crossplane-xrd
  lifecycle: experimental
  owner: group:platform
  system: fernhill-platform
  definition: |
{definition}"""


def render_apis() -> str:
    docs = []
    for api, (name, title, description, adr) in API_ENTITIES.items():
        definition = (APIS / api / "definition.yaml").read_text()
        docs.append(
            API_TEMPLATE.format(
                name=name, title=title, description=description, adr=adr,
                definition=textwrap.indent(definition, " " * 4),
            )
        )
    return "# GENERATED by scripts/gen-compositions.py from platform/apis/*/definition.yaml. Do not edit.\n" + "---\n".join(docs)


def main() -> int:
    check = "--check" in sys.argv[1:]
    stale = []
    targets = [(APIS / api / "composition.yaml", render(api)) for api in COMPOSITIONS]
    targets.append((ROOT / "catalog" / "apis.yaml", render_apis()))
    for path, want in targets:
        if path.exists() and path.read_text() == want:
            continue
        if check:
            stale.append(path.relative_to(ROOT))
        else:
            path.write_text(want)
            print(f"wrote {path.relative_to(ROOT)}")
    if stale:
        print("Stale generated files (run scripts/gen-compositions.py):", *stale, sep="\n  ")
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
