#!/usr/bin/env python3
"""Embed each platform/apis/<api>/definition.yaml into catalog/apis.yaml.

Backstage can't resolve $text placeholders relative to file locations, so
the portal's API pages embed the XRD schema. The XRD stays the source of
truth; CI runs this with --check and fails if catalog/apis.yaml is stale.

Usage: scripts/gen-catalog.py [--check]
"""

import pathlib
import sys
import textwrap

ROOT = pathlib.Path(__file__).resolve().parent.parent
APIS = ROOT / "platform" / "apis"

# API entities for the portal (ADR-0011). Backstage can't resolve $text
# placeholders relative to file locations, so the XRD is embedded instead.
API_ENTITIES = {
    "database": ("database-api", "Database API", "A t-shirt-sized Postgres database.", "0006-database-api-and-python-compositions.md"),
    "webservice": ("webservice-api", "WebService API", "Run a long-running HTTP service on the paved road.", "0008-webservice-api.md"),
}

API_TEMPLATE = """\
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: {name}
  title: {title}
  description: {description}
  links:
    - url: https://github.com/NicPucacco/aidp/blob/main/docs/adr/{adr}
      title: Decision record
spec:
  type: crossplane-xrd
  lifecycle: experimental
  owner: group:platform
  system: fernhill-platform
  definition: |
{definition}"""


def render_apis() -> str:
    docs = []
    for api, (name, title, description, adr) in API_ENTITIES.items():
        definition = (APIS / api / "definition.yaml").read_text()
        docs.append(
            API_TEMPLATE.format(
                name=name, title=title, description=description, adr=adr,
                definition=textwrap.indent(definition, " " * 4),
            )
        )
    return "# GENERATED by scripts/gen-catalog.py from platform/apis/*/definition.yaml. Do not edit.\n" + "---\n".join(docs)


def main() -> int:
    check = "--check" in sys.argv[1:]
    stale = []
    targets = [(ROOT / "catalog" / "apis.yaml", render_apis())]
    for path, want in targets:
        if path.exists() and path.read_text() == want:
            continue
        if check:
            stale.append(path.relative_to(ROOT))
        else:
            path.write_text(want)
            print(f"wrote {path.relative_to(ROOT)}")
    if stale:
        print("Stale generated files (run scripts/gen-catalog.py):", *stale, sep="\n  ")
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
