#!/usr/bin/env python3
"""Embed each platform/apis/<api>/compose.py into its composition.yaml.

compose.py is the source of truth (it has unit tests); composition.yaml is
generated so function-python can run it. CI runs this with --check and fails
if the committed composition is stale.

Usage: scripts/gen-compositions.py [--check]
"""

import pathlib
import sys
import textwrap

ROOT = pathlib.Path(__file__).resolve().parent.parent
APIS = ROOT / "platform" / "apis"

# One entry per API: directory -> (composition name, XR kind).
COMPOSITIONS = {
    "database": ("database-cnpg", "Database"),
}

TEMPLATE = """\
# GENERATED by scripts/gen-compositions.py from compose.py. Do not edit.
apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: {name}
spec:
  compositeTypeRef:
    apiVersion: platform.fernhill.io/v1alpha1
    kind: {kind}
  mode: Pipeline
  pipeline:
    - step: compose
      functionRef:
        name: function-python
      input:
        apiVersion: python.fn.crossplane.io/v1beta1
        kind: Script
        script: |
{script}"""


def render(api: str) -> str:
    name, kind = COMPOSITIONS[api]
    script = (APIS / api / "compose.py").read_text()
    return TEMPLATE.format(name=name, kind=kind, script=textwrap.indent(script, " " * 10))


def main() -> int:
    check = "--check" in sys.argv[1:]
    stale = []
    for api in COMPOSITIONS:
        path = APIS / api / "composition.yaml"
        want = render(api)
        if path.exists() and path.read_text() == want:
            continue
        if check:
            stale.append(path.relative_to(ROOT))
        else:
            path.write_text(want)
            print(f"wrote {path.relative_to(ROOT)}")
    if stale:
        print("Stale generated compositions (run scripts/gen-compositions.py):", *stale, sep="\n  ")
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
