#!/usr/bin/env python3
"""Render each Backstage template skeleton and run the result through the
tenant gate (scripts/check-tenants.py).

A golden path that generates a PR which then fails CI is worse than no
golden path, so every template is held to the same checks as hand-written
tenant config. Skeletons use Nunjucks syntax with ${{ }} delimiters, which
Jinja2 renders identically for the subset used here.

Usage: scripts/test-templates.py
"""

import pathlib
import subprocess
import sys
import tempfile

import jinja2
import yaml

ROOT = pathlib.Path(__file__).resolve().parent.parent
TEMPLATES = ROOT / "golden-paths"

# (case name, [(skeleton dir, values)], team, service dir)
CASES = [
    (
        "web service without database",
        [("new-webservice/skeleton", {"withDatabase": False})],
        "routing",
        "route-planner",
    ),
    (
        "web service with database",
        [
            ("new-webservice/skeleton", {"withDatabase": True}),
            ("new-webservice/skeleton-database", {"size": "medium", "databaseName": "routes"}),
        ],
        "routing",
        "route-optimizer",
    ),
    (
        "standalone database",
        [("new-database/skeleton", {"size": "small", "databaseName": "events"})],
        "tracking",
        "tracking-events",
    ),
]

DEFAULTS = {
    "description": "Generated by test-templates.py",
    "image": "ghcr.io/stefanprodan/podinfo:6.15.0",
    "port": 9898,
    "healthPath": "/readyz",
    "size": "small",
    "replicas": 2,
    "expose": True,
}

env = jinja2.Environment(
    variable_start_string="${{",
    variable_end_string="}}",
    keep_trailing_newline=True,
    undefined=jinja2.StrictUndefined,
    # Backstage renders JS booleans: true/false, not True/False.
    finalize=lambda v: str(v).lower() if isinstance(v, bool) else v,
)


def render_case(out: pathlib.Path, skeletons, team, name):
    target = out / team / name
    target.mkdir(parents=True, exist_ok=True)
    for skeleton, values in skeletons:
        ctx = {"values": {**DEFAULTS, "name": name, "team": team, **values}}
        for src in (TEMPLATES / skeleton).rglob("*"):
            if src.is_file():
                rendered = env.from_string(src.read_text()).render(ctx)
                list(yaml.safe_load_all(rendered))  # must be valid YAML
                (target / src.name).write_text(rendered)


def main() -> int:
    with tempfile.TemporaryDirectory() as tmp:
        tenants = pathlib.Path(tmp) / "tenants"
        for case, skeletons, team, name in CASES:
            render_case(tenants, skeletons, team, name)
            files = ", ".join(sorted(p.name for p in (tenants / team / name).iterdir()))
            print(f"{case}: tenants/{team}/{name}/ -> {files}")
        print()
        return subprocess.run(
            [sys.executable, str(ROOT / "scripts" / "check-tenants.py"), "--tenants", str(tenants)]
        ).returncode


if __name__ == "__main__":
    sys.exit(main())
