apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{ values.name }}
  description: "${{ values.description }}"
  annotations:
    backstage.io/kubernetes-label-selector: app.kubernetes.io/name=${{ values.name }}
    backstage.io/kubernetes-namespace: ${{ values.team }}
spec:
  type: service
  lifecycle: experimental
  owner: group:${{ values.team }}
  consumesApis: [webservice-api]
{%- if values.withDatabase %}
  dependsOn: [resource:${{ values.name }}-db]
---
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: ${{ values.name }}-db
  description: Postgres for ${{ values.name }} (Database API).
spec:
  type: database
  owner: group:${{ values.team }}
  dependsOn: [api:database-api]
{%- endif %}
